#Crear un pipeline que sume dos numeros dados por variables de entorno en Github y
#que muestre un mensaje dependiendo de si el resultado de la suma mayor a 10 o menor/igual a 10.

#La ejecucion fue exitosa en Github actions
#El workflow tiene un nombre
#El workflow usa el runner de ubuntu-latest
#El workflow usa el evento push
#El workflow tiene en el desencadenador el filtro de rama para cualquier nombre que empiece por test/
#El workflow usa las variables de entorno del repositorio
#El workflow usa dos jobs y un step en cada job
#Los steps y los jobs tienen un nombre
#El workflow es claro, entendible y efectivo

name: Suma de Numeros y validar el resultado

#EVENTO
on:
  push:
    branches:
      - 'test/**'

#JOBS
jobs:
  #JOB 1
  suma:
    name: sumar dos numeros
    runs-on: ubuntu-latest #RUNNER
    #STEP 1
    steps:
      - name: Configurar variables de entorno
        run: | #SHELL
          echo "SUMA=$((${{ vars.NUM1 }} + ${{ vars.NUM2 }}))" >> $GITHUB_ENV

      - name: Mostrar el resultado de la suma
        run: echo "El resultado de la suma es ${{ env.SUMA }}"

  #JOB 2
  validar_suma:
    name: validar suma
    runs-on: ubuntu-latest
    #STEP 1
    steps:
      - name: Validar si la suma es mayor a 10
        run: |
          if [ ${{ env.SUMA }} -gt 10 ]; then
            echo "La suma es mayor a 10."
          else
            echo "La suma es menor o igual a 10."
          fi